---
- name: Setup base image
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install and configure automated security updates
      ansible.builtin.include_role:
        name: automated_security_updates
    - name: Install and configure login banner
      ansible.builtin.include_role:
        name: banner
    - name: Install and configure ClamAV
      ansible.builtin.include_role:
        name: clamav
    - name: Install and configure htop
      ansible.builtin.include_role:
        name: htop
    - name: Configure JournalD to preserve logs across reboots
      ansible.builtin.include_role:
        name: persist_journald
    # Since we use Fedora (which has SELinux enabled),
    # python3-libselinux is needed to make certain downstream ansible
    # commands work; for more info:
    # https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#managed-node-requirements
    - name: Install python3-libselinux
      ansible.builtin.package:
        name:
          - python3-libselinux
    - name: Install and configure systemd-resolved
      ansible.builtin.include_role:
        name: systemd_resolved
