---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - persist_journald
    - htop
    # Since we use Fedora 31 (which has SELinux enabled),
    # libselinux-python is needed to make certain downstream ansible
    # commands work; for more info:
    # https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#managed-node-requirements
    - libselinux_python
    - clamav
