---
- hosts: all
  name: Configure for the CISA CDM environment
  vars:
    ports:
      # Tanium
      - direction: in
        port: 17472
        proto: tcp
      - direction: out
        port: 17472
        proto: tcp
      # Tanium threat response
      - direction: in
        port: 17475
        proto: tcp
      - direction: out
        port: 17475
        proto: tcp
      # Tenable
      - direction: in
        port: 8834
        proto: tcp
      - direction: out
        port: 8834
        proto: tcp
  become: yes
  become_method: sudo
  roles:
    - role: cdm_tanium_client
      vars:
        server_name: "{{ lookup('aws_ssm', '/cdm/tanium_hostname') }}"
        third_party_bucket_name: "{{ build_bucket }}"
    - role: cdm_nessus_agent
      vars:
        hostname: "{{ lookup('aws_ssm', '/cdm/nessus_hostname') }}"
        key: "{{ lookup('aws_ssm', '/cdm/nessus_key') }}"
        nessus_groups: COOL_Fed_32
        port: "{{ lookup('aws_ssm', '/cdm/nessus_port') }}"
        third_party_bucket_name: "{{ build_bucket }}"
  tasks:
    - name: Configure UFW for CISA CDM traffic
      community.general.ufw:
        comment: >
          Allow {{ item.port }} {{ item.direction }} via
          {{ item.proto | upper }}
        direction: "{{ item.direction }}"
        proto: "{{ item.proto }}"
        rule: allow
        to_port: "{{ item.port }}"
      loop: "{{ ports }}"
