---
- hosts: all
  name: Configure for the CISA CDM environment
  become: yes
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install CDM Tanium client
      ansible.builtin.include_role:
        name: cdm_tanium_client
      vars:
        server_name: "{{ lookup('aws_ssm', '/cdm/tanium_hostname') }}"
        third_party_bucket_name: "{{ build_bucket }}"
    - name: Install CDM Nessus agent
      ansible.builtin.include_role:
        name: cdm_nessus_agent
      vars:
        third_party_bucket_name: "{{ build_bucket }}"
    # The Python code that will be run by cloud-init to link the
    # Nessus Agent will require boto3
    - name: Install boto3
      ansible.builtin.package:
        name:
          - python3-boto3
    - name: Configure UFW for CISA CDM traffic
      community.general.ufw:
        comment: >
          Allow {{ item.port }} {{ item.direction }} via
          {{ item.proto | upper }}
        direction: "{{ item.direction }}"
        proto: "{{ item.proto }}"
        rule: allow
        to_port: "{{ item.port }}"
      loop: "{{ ports }}"
      vars:
        ports:
          # Tanium
          - direction: in
            port: 17472
            proto: tcp
          - direction: out
            port: 17472
            proto: tcp
          # Tanium threat response
          - direction: in
            port: 17475
            proto: tcp
          - direction: out
            port: 17475
            proto: tcp
          # Tenable
          - direction: in
            port: 8834
            proto: tcp
          - direction: out
            port: 8834
            proto: tcp
