---
- name: Configure for the CISA CDM environment
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install CDM Nessus agent
      ansible.builtin.include_role:
        name: cdm_nessus_agent
      vars:
        cdm_nessus_agent_third_party_bucket_name: "{{ build_bucket }}"
    # The Python code that will be run by cloud-init to link the
    # Nessus Agent will require boto3
    - name: Install boto3
      ansible.builtin.package:
        name:
          - python3-boto3
    - name: Install CDM CrowdStrike
      ansible.builtin.include_role:
        name: crowdstrike
      vars:
        crowdstrike_third_party_bucket_name: "{{ build_bucket }}"
    - name: Configure UFW for CISA CDM traffic
      community.general.ufw:
        comment: >
          Allow {{ item.port }} {{ item.direction }} via
          {{ item.proto | upper }}
        direction: "{{ item.direction }}"
        proto: "{{ item.proto }}"
        rule: allow
        to_port: "{{ item.port }}"
      loop: "{{ ports }}"
      vars:
        ports:
          # CrowdStrike
          - direction: out
            port: 443
            proto: tcp
          # Tenable
          - direction: in
            port: 8834
            proto: tcp
          - direction: out
            port: 8834
            proto: tcp
