---
- hosts: all
  name: Install FreeIPA server
  become: yes
  become_method: sudo
  roles:
    - freeipa_server
  tasks:
    # boto3 will be needed to pull certificates from S3
    - name: Install boto3
      pip:
        executable: pip3
        name:
          - boto3
