---
- hosts: all
  name: Hardening tasks
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Harden system
      # This role is forked from konstruktoid/ansible-role-hardening
      # and we do not control the names of the role variables.  This
      # is the reason for the noqa comment.
      ansible.builtin.include_role:  # noqa var-naming[no-role-prefix]
        name: harden
      vars:
        # FreeIPA will not install with a umask of 027
        umask_value: "022"
