---
- hosts: all
  name: Hardening tasks
  become: yes
  become_method: sudo
  tasks:
    - name: Hardening
      ansible.builtin.include_role:
        name: harden
      vars:
        # FreeIPA will not install with a umask of 027
        umask_value: "022"
