---
- name: Import base image playbook
  import_playbook: base.yml

- name: Import cloud-init playbook
  import_playbook: cloud_init.yml

- name: Import UFW playbook
  import_playbook: ufw.yml

- name: Import FreeIPA playbook
  ansible.builtin.import_playbook: freeipa.yml

- name: Import VENOM playbook
  ansible.builtin.import_playbook: venom.yml

- name: Import AWS playbook
  import_playbook: aws.yml

- name: Import hardening playbook
  import_playbook: harden.yml
