---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import automated security updates playbook
  ansible.builtin.import_playbook: automated-security-updates.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import FreeIPA playbook
  ansible.builtin.import_playbook: freeipa.yml

- name: Import CISA CDM playbook
  ansible.builtin.import_playbook: cdm.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import hardening playbook
  ansible.builtin.import_playbook: harden.yml
