---
- hosts: all
  name: Install and configure ufw
  become: yes
  become_method: sudo
  roles:
    - ufw
  tasks:
    - name: Allow incoming traffic through TCP ports
      ufw:
        comment: Allow {{ item }} via TCP
        proto: tcp
        rule: allow
        to_port: "{{ item }}"
      loop:
        - http
        - https
        - kerberos
        - kpasswd
        - ldap
        - ldaps
    - name: Allow incoming traffic through UDP ports
      ufw:
        comment: Allow {{ item }} via UDP
        proto: udp
        rule: allow
        to_port: "{{ item }}"
      loop:
        - kerberos
        - kpasswd
    - name: Allow ssh only from localhost
      ufw:
        comment: Allow ssh only from localhost
        direction: in
        interface: lo
        proto: tcp
        rule: allow
        to_port: ssh
