---
- name: Install and configure ufw
  hosts: all
  vars:
    incoming_and_outgoing_ports:
      - port: http
        proto: tcp
      - port: https
        proto: tcp
      - port: kerberos
        proto: tcp
      - port: kerberos
        proto: udp
      - port: kpasswd
        proto: tcp
      - port: kpasswd
        proto: udp
      - port: ldap
        proto: tcp
      - port: ldaps
        proto: tcp
    outgoing_only_ports:
      - port: domain
        proto: tcp
      - port: domain
        proto: udp
  become: yes
  become_method: sudo
  roles:
    - ufw
  tasks:
    - name: Set default policies to deny
      ufw:
        default: deny
        direction: "{{ item }}"
      loop:
        - incoming
        - outgoing
        - routed
    - name: Allow incoming traffic
      ufw:
        comment: Allow {{ item.port }} via {{ item.proto | upper }}
        proto: "{{ item.proto }}"
        rule: allow
        to_port: "{{ item.port }}"
      loop: "{{ incoming_and_outgoing_ports }}"
    - name: Allow ssh only from localhost
      ufw:
        comment: Allow ssh only from localhost
        direction: in
        interface: lo
        proto: tcp
        rule: allow
        to_port: ssh
    - name: Allow outgoing traffic
      ufw:
        comment: Allow {{ item.port }} via {{ item.proto | upper }}
        direction: out
        proto: "{{ item.proto }}"
        rule: allow
        to_port: "{{ item.port }}"
      loop: "{{ incoming_and_outgoing_ports + outgoing_only_ports }}"
